language: r
sudo: required
warnings_are_errors: false
addons:
  postgresql: "9.4"
r_github_packages:
  - rstats-db/DBI
  - robertzk/RPostgres@0.1.1
  - hadley/testthat
  - robertzk/testthatsomemore
  - robertzk/berdie
  - kirillseva/covr
  - avantcredit/dbtest
  - peterhurford/batchman@1.0.0.9001
r_binary_packages:
  - yaml
  - digest
  - plyr
before_script:
  - psql -c 'create database travis;' -U postgres
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  hipchat:
    rooms:
      secure: C/QSVCJr0J4eLU1IF+yFOc0Az5I2oZC/F61b1Gb3OHm2ZtLTTJY+tTD1xO0PMp+FRdDLkV9PpFWei3C+tPOMVQrzHgpB9YL3RCsHbghzH3C9O7eexQMEON1xh4cI+09F+N6CisIdeQYsUEaePZ2/sOGjo1tcBdwxSjKttGslZlw=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
