language: c
sudo: false
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended
      - pandoc
  postgresql: "9.4"
env:
  - R_LIBS_USER=~/.R/library
cache:
  directories:
    $R_LIBS_USER
before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0L) { install.packages("devtools", repos = "http://cran.rstudio.com") }'
  - Rscript -e 'devtools::update_packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'devtools::install_github("rstats-db/DBI")'
  - Rscript -e 'devtools::install_github("robertzk/RPostgres@0.1.1")'
  - Rscript -e 'devtools::install_github("hadley/testthat")'
  - Rscript -e 'devtools::install_github("robertzk/testthatsomemore")'
  - Rscript -e 'devtools::install_github("robertzk/berdie")'
  - Rscript -e 'devtools::install_github("kirillseva/covr")'
  - Rscript -e 'devtools::install_github("avantcredit/dbtest")'
  - Rscript -e 'devtools::install_github("peterhurford/batchman@1.0.0.9001")'
  - Rscript -e 'devtools::install_deps(repos = "http://cran.rstudio.com", dependencies = TRUE)'
script:
  - Rscript -e 'devtools::check()'
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  hipchat:
    rooms:
      secure: C/QSVCJr0J4eLU1IF+yFOc0Az5I2oZC/F61b1Gb3OHm2ZtLTTJY+tTD1xO0PMp+FRdDLkV9PpFWei3C+tPOMVQrzHgpB9YL3RCsHbghzH3C9O7eexQMEON1xh4cI+09F+N6CisIdeQYsUEaePZ2/sOGjo1tcBdwxSjKttGslZlw=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
